import { Genre } from "@prisma/client";
import prismadb from "../lib/prismadb";

interface Movie {
    title: string,
    description: string,
    imageUrl: string,
    imageTitle: string,
    thumbnailUrl: string,
    trailerUrl: string,
    videoUrl: string,
    year: number,
    duration: string,
    limit: number,
    genre: Genre[],
    isSeries: boolean,
}
const Movies: Movie[] = [
    // {
    //     title: "Parasite",
    //     description: "A poor family schemes to become employed by a wealthy family by infiltrating their household.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2019,
    //     duration: "2h 12m",
    //     limit: 16,
    //     genre: ["Drama", "Thriller"],
    //     isSeries: false
    // },
    // {
    //     title: "Daredevil",
    //     description: "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2015,
    //     duration: "3 Seasons",
    //     limit: 18,
    //     genre: ["Action", "Crime"],
    //     isSeries: true
    //   },
    // {
    //     title: "Black Mirror",
    //     description: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2011,
    //     duration: "5 Seasons",
    //     limit: 18,
    //     genre: ["SciFi", "Drama"],
    //     isSeries: true
    // },
    // {
    //     title: "Cobra Kai",
    //     description: "Decades after their 1984 All Valley Karate Tournament bout, Johnny Lawrence and Daniel LaRusso reignite their rivalry.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2018,
    //     duration: "4 Seasons",
    //     limit: 13,
    //     genre: ["Action", "Comedy"],
    //     isSeries: true
    //   },
    // {
    //     title: "Lucifer",
    //     description: "Lucifer Morningstar, the Devil, abandons Hell for Los Angeles where he runs a nightclub and becomes a consultant to the LAPD.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2016,
    //     duration: "6 Seasons",
    //     limit: 18,
    //     genre: ["Crime", "Drama"],
    //     isSeries: true
    //   },
    // {
    //     title: "The Queen's Gambit",
    //     description: "Orphaned chess prodigy Beth Harmon struggles with addiction in a quest to become the greatest chess player in the world.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2020,
    //     duration: "1 Season",
    //     limit: 16,
    //     genre: ["Drama"],
    //     isSeries: true
    //   },
    // {
    //     title: "The Crown",
    //     description: "A dramatized history of the reign of Queen Elizabeth II.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2016,
    //     duration: "4 Seasons",
    //     limit: 16,
    //     genre: ["Drama", "History"],
    //     isSeries: true
    // },
    // {
    //     title: "Guardians of the Galaxy",
    //     description: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2014,
    //     duration: "2h 1m",
    //     limit: 13,
    //     genre: ["Action", "Adventure"],
    //     isSeries: false
    // },
    // {
    //     title: "The Irishman (2019)",
    //     description: "A mob hitman recalls his past as a hired killer working for the Bufalino crime family in the post-World War II era.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2019,
    //     duration: "3h 29min",
    //     limit: 17,
    //     genre: ["Crime", "Drama", "Biography"],
    //     isSeries: false,
    // },
    // {
    //     title: "The Office",
    //     description: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2005,
    //     duration: "9 Seasons",
    //     limit: 13,
    //     genre: ["Comedy"],
    //     isSeries: true
    // },
    // {
    //     title: "Parasite (2019)",
    //     description: "The members of a poor family scheme to become employed by a wealthy family.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2019,
    //     duration: "2h 12min",
    //     limit: 18,
    //     genre: ["Thriller", "Comedy", "Drama"],
    //     isSeries: false,
    // },
    // {
    //     title: "Chernobyl",
    //     description: "A dramatization of the true story of the nuclear plant disaster and the men and women who sacrificed to save Europe from unimaginable disaster.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2019,
    //     duration: "1 Season",
    //     limit: 18,
    //     genre: ["Drama", "History"],
    //     isSeries: true
    // },
    // {
    //     title: "Bird Box",
    //     description: "Five years after an ominous unseen presence drives most of society to suicide, a mother and her two children make a desperate bid to reach safety.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2018,
    //     duration: "2h 4m",
    //     limit: 18,
    //     genre: ["Drama", "Horror"],
    //     isSeries: false
    //   },
    //   {
    //     title: "The Haunting of Hill House",
    //     description: "Flashbacks reveal a family's experience with the haunted house in this supernatural drama.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2018,
    //     duration: "1 Season",
    //     limit: 18,
    //     genre: ["Horror", "Drama"],
    //     isSeries: true
    //   },
    //   {
    //     title: "Extraction",
    //     description: "A black-market mercenary's mission to rescue an Indian crime lord's kidnapped son in Dhaka, Bangladesh goes awry.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2020,
    //     duration: "1h 56m",
    //     limit: 18,
    //     genre: ["Action", "Thriller"],
    //     isSeries: false
    //   },
    //   {
    //     title: "The Old Guard",
    //     description: "A group of centuries-old immortal mercenaries are suddenly targeted and must fight to keep their identity a secret.",
    //     imageUrl: "",
    //     imageTitle: "",
    //     thumbnailUrl: "",
    //     trailerUrl: "",
    //     videoUrl: "",
    //     year: 2020,
    //     duration: "2h 5m",
    //     limit: 18,
    //     genre: ["Action", "Adventure"],
    //     isSeries: false
    //   }
];

export default Movies;
